---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vizier-pem
spec:
  selector:
    matchLabels:
      name: vizier-pem
  template:
    spec:
      containers:
      - name: pem
        volumeMounts:
        - name: host-qux
          mountPath: /xhost/qux
          readOnly: true
      volumes:
      - name: host-qux
        hostPath:
          path: /qux
          type: Directory
